services:
  db:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: box4516
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
